fix validate flow

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -46,14 +46,14 @@ jobs:
         shell: bash
         run: |
           hacs_req=$(yq -r -oj .homeassistant hacs.json) || exit
-          requirements_req=$(
-            content=$(<requirements.txt) || exit
+          project_req=$(
+            content=$(<pyproject.toml) || exit
             if [[ "$content" =~ homeassistant==([0-9.]+) ]]; then
               echo "${BASH_REMATCH[1]}"
             fi
           )
 
-          if [ "$hacs_req" != "$requirements_req" ]; then
-            echo "::error file=hacs.json::HACS version requirement for HA doesn't match requirement from requirements.txt"
+          if [ "$hacs_req" != "$project_req" ]; then
+            echo "::error file=hacs.json::HACS version requirement for HA doesn't match requirement from pyproject.toml"
             exit 1
           fi
